### ISSUE TITLE
Join fails due to type confusion for String

### ISSUE THREAD

**Issue by SteffenBach** [audienceproject/crossbow#2]
The following example:
```scala
import com.audienceproject.crossbow.Implicits._

object Crossbow extends App {

  case class Score(name: String, points: Int)

  val scores = Seq(
    Score("abc", 20),
    Score("def", 15),
    Score("ghi", 10),
    Score("jkl", 5),
  ).flatMap(Score.unapply)
    .toDataFrame("name", "points")

  val names = Seq("abc", "jkl").toDataFrame("name")

  val filtered = scores.join(names, $"name")

  println(filtered.rowCount)
}
```

Fails like this:
```
Exception in thread "main" com.audienceproject.crossbow.exceptions.JoinException: name does not evaluate to the same type on both sides of the join.
	at com.audienceproject.crossbow.DataFrame.join(DataFrame.scala:198)
	at Crossbow$.delayedEndpoint$Crossbow$1(Crossbow.scala:17)
	at Crossbow$delayedInit$body.apply(Crossbow.scala:3)
	at scala.Function0.apply$mcV$sp(Function0.scala:39)
	at scala.Function0.apply$mcV$sp$(Function0.scala:39)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
	at scala.App.$anonfun$main$1(App.scala:76)
	at scala.App.$anonfun$main$1$adapted(App.scala:76)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
	at scala.App.main(App.scala:76)
	at scala.App.main$(App.scala:74)
	at Crossbow$.main(Crossbow.scala:3)
	at Crossbow.main(Crossbow.scala)
```

The column type of `scores.name` resolves to `scala.Predef.String` whereas `names.name` resolves to `java.lang.String` causing the strict [comparison](https://github.com/audienceproject/crossbow/blob/master/src/main/scala/com/audienceproject/crossbow/DataFrame.scala#L198) to evaluate to `false`.

**Comment by jacobfi** [comment]
Fixed in fa2f68544dd39035a6325ec11398349105cd35cd
